project_name: xmlfmt

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    # remove README and LICENSE
    files:
      - none*

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

nfpms:
- maintainer: Antonio Sun <asun@ats.l5.ca>
  description: XML formatting command line tool
  homepage: https://github.com/AntonioSun/xmlfmt
  license: MIT
  formats:
  - deb
  - rpm
  - apk
